### ISSUE TITLE
Certificate "4683" has been revoked.

### ISSUE THREAD

**Issue by Aephir** [poulou0/nextcloud-homeassistant-integration#11]
When trying to install, I get this error:
<img width="790" alt="Screenshot 2024-02-01 at 21 21 59" src="https://github.com/poulou0/nextcloud-homeassistant-integration/assets/20152788/101bc3a5-6aa7-4c9e-9c3c-097f583f4838">
<img width="469" alt="Screenshot 2024-02-01 at 21 21 51" src="https://github.com/poulou0/nextcloud-homeassistant-integration/assets/20152788/a509d530-f9ea-402b-ba04-e4fcf4b9d90f">

Any idea?

I am using [Danb35's script](https://github.com/danb35/freenas-iocage-nextcloud) for installing Nexcloud in a TrueNAS jail, and just re-installed (which means everything from data to databases and `config.php` stay as they were). You do need to reinstall some apps when doing this, though, and that's when I got the error. But only for this, all other apps installed just fine.

I'm on Nextcloud 28.0.2.

**Comment by TombaDude** [comment]
I am having the exact same problem. I think it is indeed something wrong with the app

**Comment by FunkyOwl-Net** [comment]
I have also the same problem..

**Comment by bernhardfrenking** [comment]
Same issue for me

**Comment by poulou0** [comment]
Hello, i think its because i lost the publishing certificate, so I had to ask for a new one for v0.0.3. If you try to install anything before the latest version, its revoked.

https://nextcloudappstore.readthedocs.io/en/latest/developer.html#updating-and-revoking-a-certificatep

Do you think thats the case? and if you install v0.0.3 manually, you will have all the configuration from your recovered database.

Let me know if thats enough ✌️

**Comment by Aephir** [comment]
By "install manually", do you mean installing it via CLI (not UI)? Is that just placing the contents of the tar.gz for the [v0.0.3 release](https://github.com/poulou0/nextcloud-homeassistant-integration/releases/tag/v0.0.3) in the `[...]/nextcloud/apps/` directory?

**Comment by wvogel** [comment]
> By "install manually", is that just placing the contents of the tar.gz for the [v0.0.3 release](https://github.com/poulou0/nextcloud-homeassistant-integration/releases/tag/v0.0.3) in the `[...]/nextcloud/apps/` directory?

I was able to install manually by executing
sudo -u www-data git clone https://github.com/poulou0/nextcloud-homeassistant-integration.git /var/www/nextcloud/apps/integration_homeassistant
Then i could find the app in the browser in "deactivated apps" (/settings/apps/disabled) as "Home Assistant Integration" and activate it. hth

**Comment by poulou0** [comment]
Sorry for the radio silence.. I tried to release a new version hoping it will solve the certificate issue, but I run into the same problem even while I try to release..

I've reached out to the nextcloud team [here](https://github.com/nextcloud/app-certificate-requests/pull/667). If nothing comes out, I will create yet another certificate 🤞

**Comment by Rijndael1998** [comment]
Thanks for doing god's work @poulou0

**Comment by poulou0** [comment]
Im trying to resolve this here now🤞
https://github.com/nextcloud/app-certificate-requests/pull/688

**Comment by poulou0** [comment]
Took a long while, but hopefully now its fixed with v0.0.4

@Aephir @TombaDude @FunkyOwl-Net @bernhardfrenking @wvogel @Rijndael1998 and everyone else,
if you use it and feel like rating the app will be appreciated because it started going downhill after all this adventure ★★★☆☆
https://apps.nextcloud.com/apps/integration_homeassistant

**Comment by Rijndael1998** [comment]
@poulou0 I confirm on my side it installs perfectly and I no longer get the error. Left you a nice score to show my thanks. Thanks again so much for this and your project.
